import random

def dato():
    datos = ["Recycling cardboard only takes 75% of the energy required to make new cardboard.",
    "The recycling rate for cardboard in the U.S. reached a record high of nearly 97% in 2019.",
    "Around 80% of retailers and grocers recycle cardboard.",
    "70% of corrugated cardboard is recovered for recycling.",
    "Approximately 100 billion cardboard boxes are produced each year in the U.S.",
    "One ton of recycled cardboard saves 46 gallons of oil.",
    "One ton of recycled cardboard saves 9 cubic yards of landfill space.",
    "Almost half of the food in the U.S. goes to waste — nearly 3,000 pounds per second.",
    "The EPA estimates more food waste goes to the landfill than any other item, making up nearly a quarter of municipal solid waste.",
    "Each year, 119 billion pounds of food is wasted in the U.S.",
    "The value of the amount of food waste in the U.S. is estimated at more than $161 billion every year.",
    "About 30% of food in American grocery stores is thrown away.",
    "2.5 million plastic bottles are thrown away every hour in America.",
    "Recycling plastic takes 88% less energy than making it from raw materials.",
    "Enough plastic is thrown away each year to circle the earth four times.",
    "Only 12% of disposable water bottles are recycled in the U.S. each year.",
    "Plastic bags can take up to 1,000 years to decompose.",
    "Recycling one ton of plastic saves the equivalent of 1,000–2,000 gallons of gasoline.",
    "Recycling plastic saves twice as much energy as burning it in an incinerator.",
    "Polystyrene foam, also known as Styrofoam, may never fully decompose.",
    "The world produces 400 million tonnes of plastic waste each year.",
    "Recycling one ton of plastic bottles saves the equivalent energy usage of a two person household for one year.",
    "Glass can possible take more than 1 million years to break down.",
    "Glass is 100% recyclable and can be recycled endlessly without loss in quality or purity.",
    "More than 28 billion glass bottles and jars go to landfills every year. That's enough to fill two Empire State Buildings every three weeks.",
    "Recycling one glass bottle saves enough energy to light a 100-watt lightbulb for four hours.",
    "Americans use 85 million tons of paper per year which is about 680 pounds per person.",
    "70% of the total waste in offices is paper waste.",
    "Recycling one ton of paper saves 7,000 gallons of water.",
    "The average office worker uses 10,000 sheets of paper per year.",
    "American businesses use around 21 million tons of paper - with about 750,000 copies made every minute.",
    "Each ton of recycled paper can save 17 mature trees.",
    "Recycling a stack of newspaper just 3 feet high saves one tree.",
    "Approximately 1 billion trees worth of paper are thrown away every year in the U.S.",
    "The average person has the opportunity to recycle more than 25,000 cans in their life.",
    "An aluminum can can be recycled and back on a grocery store shelf as a new can in as little as 60 days.",
    "Aluminum can be recycled forever without any loss of quality.",
    "Aluminum can be recycled using only 5% of the energy used to make the product from new materials.",
    "Recycling a single aluminum can saves enough energy to power a TV for 3 hours.",
    "U.S. roadways accumulate over 51 billion pieces of litter per year.",
    "There are an estimated 6,729 pieces of litter per roadway mile.",
    "On average, there are 152 pieces of litter for every U.S. resident.",
    "The most commonly littered items are cigarette butts, food wrappers, plastic bottles, disposable cups, grocery bags, straws and aluminum beverage cans.",
    "Litter cleanups cost the U.S. an estimated $11.5 billion annually.",
    "Paying the costs, businesses pay $9.1 billion, NGOs pay $769 million, educational institutions pay $240 million and the rest is paid using your state and local tax dollars.",
    "The presence of litter in your neighborhood or community lowers property values by 7%.",
    "Packaging litter makes up 46% of litter measuring 4 inches or greater.",
    "2.6 billion pieces of food 00 plastic bottles per year.",
    "207 million items of PPE masks and gloves were found across America’s roads and waterways in 2020.",
    "An estimated 350 million plastic bags were discovered on U.S. roadways and waterways in 2020, 94.6% of which were HDPE grocery bags.",
    "100,000 marine mammals and turtles and 1 million sea birds are killed by marine plastic pollution every year.",
    "Between 10–12 million metric tons of plastic waste enters the ocean each year.",
    "Without immediate action, researchers estimate 29 million metric tons will enter the oceans annually by 2040.",
    "One million marine animals are killed by plastic marine litter every year.",
    "Both direct and indirect costs from plastic marine litter is estimated to cost the world $197 billion by 2030.",
    "A littered plastic water bottle takes 450 years to decompose; an aluminum can takes 200; a glass bottle takes 1 million.",
    "Americans throw away 25 billion Styrofoam coffee cups every year.",
    "More than 11 million tons of textiles end up in U.S. landfills each year — an average of about 70 pounds per person.",
    "Around 25 million metric tons of e-waste is thrown away each year globally.",
    "The average person generates 4.9 pounds of solid waste every day.",
    "In 2018, The U.S. generated more than 294 million tons of mpackaging litter (snack bags, candy wrappers, etc.) were identified in a 2020 survey of U.S. roadways and waterways.",
    "394.7 million fast-food cups and 423 million other fast-food packaging items were identified in the same survey.",
    "Plastic waste comprises 38.6% of all litter.",
    "An average American litters or improperly disposes of 1unicipal solid waste (MSW).",
    "The EPA estimates that 75% of the American waste stream is recyclable, but we only recycle about 30% of it.",
    "94% of the U.S. population has access to some type of recycling program.",
    "Americans generate an additional 5 million tons of waste throughout the holidays.",
    "Americans throw away enough trash in an average year to circle the earth 24 times.",
    "Electronic waste totals approximately 2% of the waste stream in the U.S",
    "On average, it costs $30 per ton to recycle trash, $50 to send it to the landfill and $65 to $75 to incinerate it."
    ]

    return random.choice(datos)