challenges = [
    "Turn off lights you’re not using.",
    "Switch to LED bulbs.",
    "Unplug devices you’re not using.",
    "Use a reusable bottle all week.",
    "Don’t use single-use plastic (straws, cutlery, bags).",
    "Pick up 10 pieces of trash outdoors.",
    "Have a meat-free day.",
    "Reuse a glass jar to store something.",
    "Plant a seed in a pot or garden and take care of it all week.",
    "Shop locally (food, crafts, etc.).",
    "Walk or bike at least 2 days this week.",
    "Research and share how recycling works in your city or community.",
    "Make compost with organic waste.",
    "Don’t use the elevator for a day.",
    "Reuse paper sheets on both sides.",
    "Don’t buy anything new this week.",
    "Do a digital cleanup (delete files and emails).",
    "Reduce paper use: try reading or taking notes only digitally this week.",
    "Use cloth bags for shopping.",
    "Wash clothes in cold water.",
    "Shower 2 minutes less.",
    "Reduce your water consumption: avoid leaving the tap running while brushing your teeth or washing dishes.",
    "Organize or participate in a reforestation or local cleanup activity.",
    "Buy bulk products without packaging.",
    "Repair something instead of throwing it away.",
    "Take a day without technology.",
    "Make your own eco-friendly cleaning product.",
    "Grow a plant or a mini garden.",
    "Don’t buy bottled water this week.",
    "Swap clothes with friends instead of buying new.",
    "Use cloth napkins or handkerchiefs.",
    "Make a list of your favorite eco-friendly products.",
    "Avoid delivery with plastic packaging.",
    "Learn about sustainable fashion.",
    "Share a recipe with seasonal ingredients.",
    "Learn to identify which waste goes into each recycling bin.",
    "Make a craft using recycled materials.",
    "Avoid products with palm oil this week.",
    "Take a no-buy challenge for 3 days.",
    "Avoid fast fashion this week.",
    "Save paper: use apps or digital notes.",
    "Cook all week without wasting food.",
    "Make a list of your favorite eco actions from the year.",
    "Avoid ultra-processed foods for 3 days.",
    "Organize an eco-friendly movie night.",
    "Write a short journal or note about what changes you made and how you felt.",
    "Research an environmental policy or law that interests you.",
    "Buy or swap something secondhand this week.",
    "Do a 24-hour plastic-free challenge.",
    "Check your energy consumption for the month.",
    "Create a personal or community eco guide.",
    "Celebrate your progress: share your green experience from the year."
]