import random

def tip():
    tips = ["Borrow instead of buying.",
    "Use your local Community Fridge.",
    "Insulate your hot water tank.",
    "Use vinegar to tackle limescale.",
    "Draught-proof windows and doors.",
    "Opt for peat-free compost.",
    "Plug in when your energy supply is greenest.",
    "Buy more sustainable fish.",
    "Make sure your old gadgets get recycled.",
    "Choose recyclable gift wrap and greeting cards.",
    "Keep your toilet smelling fresh.",
    "Clean your microwave the eco way!.",
    "Reduce microfibres released in the wash.",
    "Make your own cleaning cloths.",
    "Descale the kettle the green way.",
    "Mulch your flower beds.",
    "Approach 'compostable' claims with caution.",
    "Plant perennials.",
    "Switch to more eco-friendly coffee pods.",
    "Make your own compost.",
    "Use greener methods to clear drains.",
    "Recycle contact lenses and packaging.",
    "Buy loose fruit and veg.",
    "Avoid palm oil.",
    "Use a microfibre cleaning cloth.",
    "Switch gadgets and appliances off when not in use.",
    "Brush up on recycling rules.",
    "Measure your carbon footprint.",
    "Recycle cosmetics packaging.",
    "Recycle at your garden centre.",
    "Make the most of your freezer.",
    "Switch to eco-friendly washing up liquid.",
    "Plant bee-friendly plants.",
    "Look out for 'green van' delivery options.",
    "Make the most of what you’ve got!",
    "Use a portion calculator.",
    "Ditch branded multi-surface cleaners.",
    "Get more life from your washing machine.",
    "Repair rather than replace.",
    "Get clever with leftovers.",
    "Clean your windows the green way.",
    "Take your own plant cuttings.",
    "Look for locally grown, seasonal produce.",
    "Ditch liquid floor cleaner.",
    "Be wary of 'biodegradable' claims.",
    "Get help to eat more veg.",
    "Use alternatives to floral foam.",
    "Eco-friendly alternatives to cling film.",
    "Don’t leave things on standby.",
    "Install a smart meter.",
    "Return fewer ítems.",
    "Choose plastic-free tea.",
    "Get your milk delivered.",
    "Refill, refill, refill.",
    "Give soluble cleaning products a go.",
    "Remember your reusable bag.",
    "Have a greener period.",
    "Rethink how you store your fruit",
    "Invest in the future.",
    "Give pre-loved gifts.",
    "Buy a reusable water bottle.",
    "Don’t let your unused food go to waste.",
    "Use a keep-cup.",
    "Give preloved and vintage clothes a second life.",
    "Buy local.",
    "Reuse plastic plant pots.",
    "Buy the most energy efficient appliances you can afford.",
    "Grow your own!",
    "Choose green delivery options when you shop online.",
    "Opt for organic."
    ]

    return random.choice(tips)